### ISSUE TITLE
Mobs don't get hostile and don't get knocked back when punching them without damage

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#100]
If you apply a punch to a mob without any damage, the mob doesn't get angry and also does not receive any knockback.

Use case for a punch without damage: Minecraft snowball. This is supposed to deal no damage, just deal knockback and anger.

Or is there a better way to apply knockback or anger to a mob?

**Comment by tenplus1** [comment]
Have added tool 'knockback' for mobs so you can hit with special item to fling them across a room without damage, will look into more precise usage.
