### ISSUE TITLE
Mob explosion punches victim by itself

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#101]
If a victim is caught in a mob explosion, the damage source is also the victim.

This becomes a problem when you want to make a death message mod where you reliably need to know the puncher.
If a mob explodes, for the death message log it appears as if the player punches himself/herself. xD

A solution would be that the damage source is the exploding mob instead of the victim.

**Comment by tenplus1** [comment]
We mostly use tnt.boom function to cause harm to mobs and player so no entity information is passed to that function at all...  If tnt mod is disabled or area protected then we use the built-in entity_physics instead which does the same (check entities in blast area and punch with themselves) for simplicity.  IF damage reason ever makes it's way into engine then this can be refined and improved in both cases.
