### ISSUE TITLE
Various problems with death animation

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#102]
Strange. I still have problems with the death animation. Namely, with the skeleton in `mobs_mc`.
https://github.com/maikerumine/mobs_mc/blob/master/skeleton%2Bstray.lua

```

	animation = {
		stand_start = 0,
		stand_end = 40,
		stand_speed = 5,
		walk_start = 40,
		walk_end = 60,
	        walk_speed = 50,
	        shoot_start = 70,
	        shoot_end = 90,
	        punch_start = 70,
	        punch_end = 90,
	        die_start = 120,
	        die_end = 130,
		die_loop = false,
	},
```

There are the following problems with a skeleton:
* On *some* deaths, the skeleton dies with a death animation which is *not* looped. Correct!
* On *some* deaths, the skeleton death animation loops like before. It seems to happen randomly. Strange …
* When I kill the skeleton shortly after spawning with the strongest weapon, no death animation is played at all. The mob just stands there, doing nothing, then disappears. It seems to happen when I manage to kill the skeleton before its first regular animation starts. When I killed the skeleton after it started animating (e.g. shoot anim), the death animation plays

I know, `die_speed` is not set (not tweaked yet). But regardless of this setting, the animation should never ever loop, right? It's just that the animation speed is the default, right?

When I set `die_speed` set, the death anim is just slower, but it doesn't seem to affect the strange behaviour I observed.

**Comment by tenplus1** [comment]
I've tweaked the animation settings which should help, also I recommend adding run_start and run_end frames for the skeleton so it doesn't slide when moving towards the player.

**Comment by Wuzzy2** [comment]
OK, will try out ASAP.
BTW: Why did you add `api.lua_`? :D

**Comment by Wuzzy2** [comment]
Sorry. This didn't help at all. The `mobs_mc` skeleton still has animation problems after the update. :-(

**Comment by tenplus1** [comment]
I'm running mc_mobs to test and the skeletons die animation seems to work ok.  Are you testing on singleplayer or server ?  Also api.lua_ was a mistake, a temp file that should have been removed.

**Comment by Wuzzy2** [comment]
I still have problems after updating the mods. I tested on singleplayer mode.

Using:
* Minetest 0.4.16
* Minetest Game 0.4.16
* `mobs` 8ad63d35d08b5dd08f2d4b6aecc0c39dc6caafc6
* `mobs_mc` 04dd0d6e02a66c4fae67f08e1a0b87a82ed09b65

**Comment by tenplus1** [comment]
I've redone the death animation timer, it now calculates frames/speed to give play time before removing mob so no more looping.

**Comment by Wuzzy2** [comment]
The bug is now fixed, but I don't like that the mob instantly disappears after the death animation is played.
Or would you say this is the responsibility of the mob animation?

**Comment by tenplus1** [comment]
If I can factor in a delay I will, but glad it's working in a way for you.
