### ISSUE TITLE
HTML API Documentation

### ISSUE THREAD

**Issue by AntumDeluge** [tenplus1/mobs_redo#105]
Not sure if you will like it, but I'm working on [converting the API docs to HTML](https://antummt.github.io/mod-mobs_redo/api.html) using [LDoc](http://stevedonovan.github.io/ldoc/) so it's easier to read. It's still unfinished.

I thought it would be a good idea because the ***mobs_redo*** API, being a library-like mod, is somewhat bigger than most other mods.

**Comment by tenplus1** [comment]
thanks
