### ISSUE TITLE
players hear hit sounds all over the map

### ISSUE THREAD

**Issue by tchncs** [tenplus1/mobs_redo#113]
Hi there, players somehow hear when other players are attacked by mobs all over the map.
As this is not the default "hit" sound but more "metallic", i am not 100% sure if this issue report should go to 3darmor instead...or maybe something completly different.. . o.O

However, mobs_redo is currently at ba167a3, 3darmor is at 0454d72 and minetest itself at d504831e.

**Comment by tenplus1** [comment]
All mob sounds are linked to the entity location and a set hearing distance so may be another mod causing issue: https://github.com/tenplus1/mobs_redo/blob/master/api.lua#L84
