### ISSUE TITLE
Knockback Broken

### ISSUE THREAD

**Issue by TekhnaeRaav** [tenplus1/mobs_redo#114]
The knock_back doesn't change with the numbers that I input when I have the mob set to "dogfight". They get knocked back a tiny bit when I hit them but it doesn't change. Also when I set it to not have an attack type, they get knocked back and just keep sliding on the ground for probably infinitely, and even then the numbers don't  seem to be doing anything.

This is my mob settings.
![capture3](https://user-images.githubusercontent.com/30163969/30516037-4c5b84d8-9af9-11e7-9368-ef02bc8863b0.PNG)

**Comment by tenplus1** [comment]
Knockback default is 3 and that generally hits the mob half a block backwards, try a higher number.
