### ISSUE TITLE
"Shoot" Type Mobs Aim Under You

### ISSUE THREAD

**Issue by TekhnaeRaav** [tenplus1/mobs_redo#116]
I've created a mob with working arrows but the mobs always aim there shots under you and start hitting the ground. They start hitting you a little if your jumping, but that's just because they start aiming a little higher.

I also noticed this with some mob mods that were made for mobs_redo.

**Comment by tenplus1** [comment]
use the shoot_offset variable in mob definition to fix this.

**Comment by TekhnaeRaav** [comment]
Oh. Thank you : )
