### ISSUE TITLE
Dogshoot Range Setting Request

### ISSUE THREAD

**Issue by TekhnaeRaav** [tenplus1/mobs_redo#119]
It would be helpful to have a setting for "dogshoot" type mobs that lets you set a range at which the mob will chase you (dogfight), and a second range that (would be set by view_range) that the mob should shoot at you.

Something like this,

view_range = 12,
dogfight_range = 6,   --or "shoot_range" if you want to have him shoot closer and chase farther--

So with this setting the mob would see and shoot at you from 12 and chase and punch at 6.
Am I making any sense?

**Comment by tenplus1** [comment]
Dogshoot mode already has 2 ranges set, one is self.reach for dogfight attack and the other is self.view_range for shooting attack.  If you use self.dogswitch then it switches between the two so that the mob CAN chase the player and shoot at them independently of range/reach.

**Comment by TekhnaeRaav** [comment]
Reach is where the mob actually is able to hit you, so at this point of range the mob wouldn't chase, it would just hit you.
So another range would allow for the mob to chase you before hitting you.
