### ISSUE TITLE
HP labels/nametags not showing

### ISSUE THREAD

**Issue by taikedz** [tenplus1/mobs_redo#12]
Hello

I'm running a server (0.4.13 from PPA) on which I have loaded a few mobs; unfortunately the nametags/HP labels are not displaying.

Main question: is there a version requirement on mobs_redo?

Further details:

If I run the same set of mods in my client (0.4.13, also from PPA), I do see them, except when using maikerumine's esmobs. On the server I do *not* have esmobs.

I tried adding a bunch of debug statements to the feed_tame function and it seems all parts are being called correctly (it steps through fine, at least) so I'm not sure where to go from there... All I can further note is that the update_tag seems to only run after the feed_tame function exits (added debug printouts along feed_tame of which one "feed tame end" right before the final return; and one debug at the end of update_tag), which does not sound intuitive to me...

	function mobs:feed_tame(self, clicker, feed_count, breed, tame)
		mydebug("start feed")
	 ....

		mydebug("end feed")
		return false

	end

	....

	function update_tag(self)

		local col = "#00FF00"
		local qua = self.hp_max / 4

		if self.health <= floor(qua * 3) then
		        col = "#FFFF00"
		end

		if self.health <= floor(qua * 2) then
		        col = "#FF6600"
		end

		if self.health <= floor(qua) then
		        col = "#FF0000"
		end

		mydebug("Updating nametag: "..col)

		self.object:set_properties({
		        nametag = self.nametag,
		        nametag_color = col
		})

	end

The log shows

	2016-07-25 09:08:41: ACTION[ServerThread]: taikedz right-clicks object 44: LuaEntitySAO at (-48.485,8,46.8572)
	start feed
	Attempt rename
	end feed
	Updating nametag :#FF0000
	2016-07-25 09:08:50: ACTION[ServerThread]: taikedz leaves game. List of players:

**Comment by everamzah** [comment]
You need a newer version of Minetest.  I believe 0.4.14 features the nametags.

**Comment by everamzah** [comment]
From http://www.minetest.net/downloads/

http://packages.ubuntu.com/search?keywords=minetest
https://launchpad.net/~minetestdevs/+archive/ubuntu/stable

**Comment by taikedz** [comment]
minetest client in PPA is 0.4.14 indeed

minetest-server latest in PPA is still 0.4.13 http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=minetest-server&searchon=names ; I'll need to see about compiling a new version then.... I don't like leaving build tools on internet-facing servers.... I'll see.

Or maybe I just run a Ubuntu server as beta and use the 0.4.14 build from yakety....!

**Comment by everamzah** [comment]
I'd compile it on another computer and scp it to the host.
