### ISSUE TITLE
Dogfight mob type dosen't chase straight to player

### ISSUE THREAD

**Issue by TekhnaeRaav** [tenplus1/mobs_redo#120]
The mobs when in "dogfight" mode chase the player, but follow him in kind of a grid pattern, and don't walk diagonally until very close to a player.
However the "dogshoot" mobs when chasing go straight toward the player.

**Comment by TekhnaeRaav** [comment]
With my dogfight mob I had pathfinding set to zero to just turn it off for a second, but apparently the 0 value does the same thing as the 1 value so that was the problem on dog-fighters. Still the dogshoot mobs were not using pathfinding on chase. Do they have pathfinding?

**Comment by tenplus1** [comment]
Pathfinding only happens with mobs that follow you when attacking, will look into that...
