### ISSUE TITLE
explosion_radius increases mobs damage

### ISSUE THREAD

**Issue by TekhnaeRaav** [tenplus1/mobs_redo#121]
The bigger the explosion radius the more damage the explosion does, this makes it very difficult to get the desired damage.

**Comment by tenplus1** [comment]
i don't understand this issue

**Comment by TekhnaeRaav** [comment]
I did some testing and no matter how much the damage is set to on "explode" type mobs, the damage only changes depending on the explosion_radius.
This is my version--minetest-0.4.16

**Comment by tenplus1** [comment]
The damage setting is mainly for melee attacks like punch, not explosion damage which is calculated using radius.

**Comment by TekhnaeRaav** [comment]
Is it _possible_ to set an overall damage for the explosion that doesn't change depending on range?
