### ISSUE TITLE
block_destroy setting for "explode" type mobs

### ISSUE THREAD

**Issue by TekhnaeRaav** [tenplus1/mobs_redo#123]
Hi! Got another one.
There should be a setting that sets whether or not the explosion of "explode" type mobs destroys blocks.
Maybe even a table with a list of blocks that the explosion can destroy.

**Comment by tenplus1** [comment]
this u can add

**Comment by Wuzzy2** [comment]
This is the wrong approach. Just fix the `on_blast` definition of the affected nodes.
