### ISSUE TITLE
The mobs jump on the carpet

### ISSUE THREAD

**Issue by BrunoMine** [tenplus1/mobs_redo#124]
The mobs jump incessantly over any decorative node on the ground.
That makes them jump until they get in some wall.

Screenshot of [sociedades](https://forum.minetest.net/viewtopic.php?t=15382) mod
![erro mobs](https://user-images.githubusercontent.com/7986261/31309601-053de782-ab5f-11e7-9e9d-ddcfdb0e2e7f.png)

**Comment by tenplus1** [comment]
make carpet walkable=false for now.
