### ISSUE TITLE
Animals attack back?!

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#127]
The ocelot in `mobs_mc` is a mob of type `“animal"`, but if the player attack it, the ocelot attacks back (instead of fleeing).

Ocelot code:
https://github.com/maikerumine/mobs_mc/blob/master/ocelot.lua#L31

I think I got it right:

* `type="animal"`
* `passive=false`
* `runaway=true`

According to docs:

>  "animal" usually docile and walking around.

> 'passive'       when true allows animals to defend themselves when hit,
                   otherwise they amble onwards.

>  'runaway' if true causes animals to turn and run away when hit.

(BTW: What does “usually” mean? Can't the description of the animal type be more specific? IMO all types need much more detailed description, so that modders can better predict the mob behaviour.)

**Comment by tenplus1** [comment]
If you dont want an animal fighting back then set docile=true.
