### ISSUE TITLE
Big mobs spawn in small spaces

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#128]
A common problem with big mobs (larger than 1×1×1) is that they can spawn in small spaces. This can be very annoying and I consider this to be a bug.

For example, if you have a mob of a cube shape with size 3×3×3, it is very possible that this mob spawns in areas tighter than that, overlapping with solid nodes.

I suggest for all mobs to implement a space requirement. To make things easier for modders, the required space could be calculated automatically.

The spawn algorith for large mobs could be like this:

All mobs smaller than (1,1,1) spawn like they do now, nothing changes.
For all other mobs:
First, take the size of the collision box, and round each number up. If a number was already an integer, add 1 anyway.
E.g. (2.5, 2.5, 1) → (3, 3, 2)

The new size box you calculated is the new space requirement of this mob, in nodes. Each of these nodes have to be free (=non-walkable, like air, flower, grass, but not stone or wall). If the mod found such an area, the mob will be spawned in this box: horizontally at the center, and vertically at the bottom.

With this algorithm, mobs should now never spawn in tight spaces again.

**Comment by tenplus1** [comment]
api now checks for height clearance befrore spawning mobs.
