### ISSUE TITLE
Swimming mods (fish, squids, etc.) can get stranded

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#129]
It seems the behaviour of swimming mobs in the water, using `floating=1` (e.g. fish) is not really smart.
It often happens that these mobs get stranded and can't move.

Evidence for this can be found in the mod `mobs_mc`. Watch the squid, guardian or elder guardian in water.

If they are close to the beach, and swim towards it, they climb up the beach and get stuck.
You can provoke this by punching them towards the beach.

The mobs will just climb up the beach as it were stairs.

This is also the case if you set `step_height=0`. There doesn't seem to be a workaround.

**Comment by R-0ne** [comment]
hi,

I don't use mobs_mc but in mobs_water is solve with : 

jump =false,
stepheight = 0.1,

I do not know if it works for you, but can you try?
