### ISSUE TITLE
allow mobspawn for specific biomes

### ISSUE THREAD

**Issue by tchncs** [tenplus1/mobs_redo#13]
hi there, i just noticed that there are actually [biomenames](https://github.com/minetest/minetest_game/blob/master/mods/default/mapgen.lua#L486).
Now i wich to be able to define mob spawns for this specific areas.

I dont know if it's possible already using some lua tricks since i don't have that experience for it so i created this issue just in case :)

Kind regards, thanks for mobs_redo :)

**Comment by MarkuBu** [comment]
This is only possible while map generation. If the map is generated the biome information is lost

**Comment by tchncs** [comment]
Oh, thats sad, thanks for the information.

**Comment by MarkuBu** [comment]
You can register a mapgen function where you can place spawners while map generation. While map generation informations like biomemap and heightmap are available.

Once the map is generated all informations are lost

**Comment by tchncs** [comment]
Well, thats a problem since we pregenerated a huge part of our map but this is good to know. 
Thank you again @MarkuBu.
