### ISSUE TITLE
Add mobs.registered_spawns

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#133]
I suggest to add a global table `mobs.registered_spawns`, analog to `minetest.registered_items`.

This table contains all mob spawn rules.

E.g.the value of `mobs.registered_spawns["mobs:giraffe"]` contains the spawn definition table of the mob `mobs:giraffe`.

**Comment by tenplus1** [comment]
what would the usage be ?

**Comment by Wuzzy2** [comment]
So I can learn where mobs spawn.

**Comment by Wuzzy2** [comment]
Concrete use case: Mob spawner with a zombie only spawns zombies in the dark. To make it work in a generic fashion, I don't want to hardcode zombies for this to work, but to read the light values from the spawn definition directly. :-)

See also: https://github.com/tenplus1/mobs_redo/pull/134
