### ISSUE TITLE
Spawn hostile mobs further away from player

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#141]
Sometimes, hostile mobs can spawn dangerously close to a player.
I understand why mobs spawn out of nowhere but at least the player should have a chance to react.
If you have exploding mobs like a creeper or a mine turtle, this can be very unfair as the game is basically throwing bombs right before your feet! XD

I propose a default distance of at least 16 blocks away. Or maybe, maybe 8. The trick is not to make this number so high that no more mobs would spawn.

Bonus points if you make the distance settable per-mob, but this is not that important.
Peaceful mobs should be still allowed to spawn anywhere.

**Comment by tenplus1** [comment]
I already spawn mobs 12 blocks away from the player, but sometimes the player is walking towards the mod in question when it's spawning :)  Anything over 12 and it could be outside the loaded map boundaries.
