### ISSUE TITLE
Disorganization

### ISSUE THREAD

**Issue by BrunoMine** [tenplus1/mobs_redo#15]
This mod was [never released](https://github.com/tenplus1/mobs_redo/releases)? This means that there is no version control and it is vital for MOB-Engine.

**Comment by tenplus1** [comment]
Mobs Redo API is a rolling release.

**Comment by BrunoMine** [comment]
You should study a little organizing software projects. I was like you, just change the code and ready, but this is not interesting because you have no progress control, errors, etc.
