### ISSUE TITLE
knock_back = true crashes the game

### ISSUE THREAD

**Issue by H4mlet** [tenplus1/mobs_redo#156]
api.txt @ 53
> 'knock_back'    when true has mobs falling backwards when hit, the greater the damage the more they move back.

--- debug start
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'mobs_test' in callback luaentity_Punch(): .../mods/mobs/api.lua:2398: attempt to compare number with boolean
--- debug end

"knock_back = 1" works fine

**Comment by tenplus1** [comment]
Fixed :) thanks...
