### ISSUE TITLE
The function line_of_sight in api.lua makes no sense

### ISSUE THREAD

**Issue by mtango688** [tenplus1/mobs_redo#158]
Please explain how the while loop is supposed to work. I've been staring at the code for an hour, and it just doesn't make any sense how it's supposed to work.

**Comment by tenplus1** [comment]
You have direct line of sight then it'll start checking if mob can see through plantlike/water nodes also with a manual check.

**Comment by mtango688** [comment]
I understand that. But it clearly isn't doing that. The code literally does nothing. The variable npos1 never changes through each iteration, the variables r and pos only change the first time, and the only reason it ever escapes the while loop is when ad increments that it breaks out of the loop, thus serving no logical purpose.
