### ISSUE TITLE
How to control the crowds of creatures?

### ISSUE THREAD

**Issue by BrunoMine** [tenplus1/mobs_redo#16]
I remember that the mod mobs (of PilzAdam) had a problem of creatures crowds on the server. I believe it is because of mobs forever remain on the map.
How mobs_redo solved it?

**Comment by tenplus1** [comment]
Yes, we disable catch_up on the spawn abm so that groups of mobs will never spawn (unless set to do so), also a minetest.conf setting 'remove_far_mobs = true' will remove any mob that is outside the current loaded area unless it has been tamed or an npc.
