### ISSUE TITLE
feature request: allow to override mobs' settings

### ISSUE THREAD

**Issue by Kathbaph** [tenplus1/mobs_redo#161]
it is already possible to override spawn chance and AOC by adding a line to minetest.conf, but one can't modify min_height, max_light, spawn_nodes, etc.
this would allow to easily tune any mob using this API instead of changing the hardcoded values

**Comment by tenplus1** [comment]
These are more of a per-server setting for owners to adjust code settings, but I will look into a settings file that could possible alter mob spawn settings.
