### ISSUE TITLE
Mob nametag does not take mob height into account

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#166]
If you give a name tag to mobs, it is always at the same height, regardless of the actual mob height.
This means, for rather high mobs, the name tag might be written in the body of the mob, rather than above the head.

**Comment by tenplus1** [comment]
As far as I'm aware we have no control over this, the nametag applied to an entity appears where it appears.

**Comment by Wuzzy2** [comment]
Good point, thanks.

**Comment by H4mlet** [comment]
I guess that an answer was too expensive.
