### ISSUE TITLE
minetest.after calls are possible places for crash

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#167]
There are many ways in Mobs Redo to crash. This is a quite sneaky critical bug.

The code frequently feeds objectrefs and players objectrefs into `minetest.after`, but they are not-rechecked in the embedded function. If the object is destroyed in the meanwhile (e.g. player disconnected, mob killed), the server WILL crash when you try to do anything on the objectref. Please check all calls to `minetest.after`.

https://rubenwardy.com/minetest_modding_book/en/chapters/common_mistakes.html#never-store-objectrefs-ie-players-or-entities

**Comment by tenplus1** [comment]
Fixed by adding entity checks.

**Comment by Wuzzy2** [comment]
It can still crash, you forgot `mount.lua`. There are player objectrefs which might disappear in the time.
