### ISSUE TITLE
Nothing spawns in ethereal

### ISSUE THREAD

**Issue by techgnosis** [tenplus1/mobs_redo#20]
Hey

You also wrote ethereal so you can probably help. I've got mobs_animal and mobs_monster loaded but nothing seems to spawn in ethereal. Is this by design or am I just imagining things?

**Comment by tenplus1** [comment]
Mobs do spawn but not as often as before (catchup was disabled), also any active entities in an area (dropped items, itemframes, mobs) will limit new mobs from spawning so there aren't too many in one place.
