### ISSUE TITLE
Mobs deal 0 damage

### ISSUE THREAD

**Issue by JurajVajda** [tenplus1/mobs_redo#23]
Mobs deal 0 damage when player in cart or boat. I think there have to be an offset for the attack.

**Comment by JurajVajda** [comment]
Could maybe deal half of a normal damage when in boat or cart...since they give you a bit of protection.

**Comment by tenplus1** [comment]
This is a bug inside minetest itseld and an issue has been posted  on git for minetest itself.

**Comment by JurajVajda** [comment]
Hmmm..ok then..weird since MTG doesn't have mobs :) i will check it thought, thanks.

**Comment by tenplus1** [comment]
The bug is to do with attaching the player to entities like carts or boats and having no collisinobox around player when you do, so no damage can be dealt.

**Comment by BrunoMine** [comment]
there must be some way to fix this. At least for a while.
