### ISSUE TITLE
Map gets overflooded with mobs and monsters

### ISSUE THREAD

**Issue by tchncs** [tenplus1/mobs_redo#25]
Hi there, i just updated mobs_redo on my server.
It seems like the mobs are spawning heavy often and the players are not all very happy with this.
I am not sure how to decrease it since adjusting the spawn commands doesn't do that big effect... .

**Comment by BrunoMine** [comment]
you have tried to increase the value of `modname:mobname_chance`?
`
modname:mobname_chance = 10000
modname:mobname_chance = 20000
modname:mobname_chance = 30000
`
This really should reduce the spawned mobs until disappear completely.
More info: https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L13
I'm not sure, but I believe the API is wrong about this setting. The correct would be `mobs_animal:cow_chance` and not `mobs_animal:cow`.

**Comment by tchncs** [comment]
The chance thing was one thing which [confused me](https://forum.minetest.net/viewtopic.php?p=237730#p237730), on a forked dmobs mod, i guess and hope that i did this [finally right](https://git.tchncs.de/Illuna-Minetest/dragons/blob/master/dragons.lua#L1189) so the interval is 120 seconds and the chance is 90.000. As reported to me, there are after some time at least ten dragons the players have to fight (yes, there are many spawn nodes around so there are more anyway). 
So far it didn't really made a difference if i had 1sec to 1 or 120sec to 90.000.

I didn't tried yet to change the value using settings for the other mobs. 
But hey, the default spawnrate by the api is now really heavy and i think this should be decreased by default anyway...

**Comment by tenplus1** [comment]
Spawn settings were changed in latest release and you use this in minetest.conf to adjust settings:

# change cow to spawn chance 1000 with 5 per map block area
mobs_animal:cow = 1000,5

**Comment by tchncs** [comment]
It seems a way more balanced after 31db77b, thanks.
