### ISSUE TITLE
About the specific_attack 

### ISSUE THREAD

**Issue by NPXcoot** [tenplus1/mobs_redo#29]
Two problems:
 - in "api.txt" there's written "attack_specific" instead of "specific_attack"
 - in "api.lua" line 1068 where there is the condition about the specific_attack it doesn't consider the possibility of a monster attacking other monsters. This could be a funny addition!

**Comment by tenplus1** [comment]
I'll look into monsters vs monsters (godzilla vs mothra :), would be funny but the attack detection would need to be re-written for that.
