### ISSUE TITLE
lucky_block and mobs_redo depend on eachother

### ISSUE THREAD

**Issue by taikedz** [tenplus1/mobs_redo#30]
`lucky_block` optionally depends on `mobs_redo` ; and vice versa

It means neither load of course, and when lots of mods report they lack dependencies it's not obvious this is the problem

**Comment by taikedz** [comment]
Can I suggest making `lucky_blocks` more engine/framework-like and allowing other mods to register a callback to it like

    lucky_blocks.register("dro","mobs:meat",4)

and

    lucky_blocks.register("dro","ethereal:crystal_spike",1)

without providing them in Lucky itself ...?

**Comment by tenplus1** [comment]
Lucky block's only dependency is 'default'.
