### ISSUE TITLE
New "hp" display is not localisable

### ISSUE THREAD

**Issue by eidy** [tenplus1/mobs_redo#32]
The new "hp 1/12" display is not localised and may be confusing to people.

I'd like to ability to customise or hide this new functionality.

For my educational game I have modified it to read "self.nametag =  self.health".

For me this looks pretty cool, as it lets the kids see numbers without worrying about the D&D "hp" term.

Possible options:
1. Provide a minetest.conf parameter like:
mobs.hpdisplayformat ="{$hpleft} / ${hp}"
2. Provide a hook to provide the nametag.  (I already override this myself under some circumstances)
3. Provide a global option to switch it off:
mobs.hpdisplay=false

**Comment by tenplus1** [comment]
We already have a 'mob_show_health' flag in minetest.conf to turn the health text on.off...  Will look into customizing string though.

**Comment by tenplus1** [comment]
Changed to a simple "♥ 1/20" style text.

**Comment by eidy** [comment]
nice.
