### ISSUE TITLE
Mobs aren't affected by nodes with 'damage_per_second'

### ISSUE THREAD

**Issue by MT-Modder** [tenplus1/mobs_redo#33]

**Comment by tenplus1** [comment]
Mobs use their own lava/water/light damage system but I'll look into adding damage_per_second node checks into the mix soon.

**Comment by MT-Modder** [comment]
Awesome thanks. It just feels kinda weird. Like when arrows from certain mods don't affect mobs.

**Comment by tenplus1** [comment]
when damaging mobs you have to use punch command and not set health, which is probably why some bows dont work.

**Comment by tenplus1** [comment]
damage_per_second check added.
