### ISSUE TITLE
mobs_water swimming sideways (back compat)

### ISSUE THREAD

**Issue by taikedz** [tenplus1/mobs_redo#34]
It seems that sometime since dec 20, a yaw change causes once-forward-swimming seaturtles and various fish, from blert2112's mobs_water, to now swim sideways... checked out 12503180 and they swim normally...

Is this a backwards-compatibility problem, or should it be fixed in mobs_water instead ?

**Comment by tenplus1** [comment]
check to see if the mob definition has any "rotate = " lines added and check it's using the right one.

**Comment by tenplus1** [comment]
Fixed.
