### ISSUE TITLE
Some mobs going round in circles

### ISSUE THREAD

**Issue by taikedz** [tenplus1/mobs_redo#37]
Ever since https://github.com/tenplus1/mobs_redo/commit/4bcfa6b802fe389535dbc62522df9dba37e7c467 , some mobs from [NSSM](https://github.com/npxcoot/nssm) circle round the player instead of coming straight for them

Steps to reproduce:

* make new world in default game
* activate nssm, mobs_redo (any version from 7th January 2017 - previous versions are OK)
* start new world
* set time 0 (easy mob to reproduce this with needs darkness)
* spawnentity nssm:signosigno and walk back from it
* see that it runs around in circles, very gradually getting nearer the player, circle uses as radius its distance from player and player as central point, over time gradually reducing the radius

This only affects a subset of mobs from nssm, consistently. Removing the `rotation` parameter from signosigno (commenting it out) does not fix the issue.

I'm not yet clued up enough on yaw calculations to suggest anything, just looking around L1778 (master 19th Jan) is where I can seem to affect the movement -- changing it to:

    yaw = (atan2(vec.z, vec.x) - pi / 2) - self.rotate

(added rotate subtraction) restores the correct directional movement (comes straight to player) but the mesh is now rotated to the side.

**Comment by tenplus1** [comment]
Check today's build to see if it persists, if so then I'll regress the codebase.

**Comment by taikedz** [comment]
3ba7def - yes that's the on I am testing with. just tried after a pull on master - same circles...

**Comment by tenplus1** [comment]
Okies, try the pull I just upped, seems to work fine here...

**Comment by taikedz** [comment]
Confirmed fixed... going to study that and maybe finally get this yaw stuff understooded.... thanks.
