### ISSUE TITLE
Add ability to customize what nodes mobs can float in

### ISSUE THREAD

**Issue by MT-Modder** [tenplus1/mobs_redo#38]
I don't know how difficult it would be to add this but could you please?

**Comment by tenplus1** [comment]
At present floating mobs will float in anything liquid (water, river water, lava) that gives them buoyancy. Can you give me an example of why a custom check would benefit mobs ?

**Comment by MT-Modder** [comment]
Well I was trying to figure out the best way for spiders to move around in their own web. Tried making them fly in it but then they can't walk in air. Then I thought maybe float would look good but for some reason it didn't work like you would imagine - they would just "flop" to the ground when inside the web. 

It was late when I requested this and I realize now it's probably better to use do_custom.

**Comment by tenplus1** [comment]
Maybe I could add command style nodes to mobs api, certain blocks will make them jump, some will stop them falling (webs) etc.

**Comment by MT-Modder** [comment]
That sounds like a really nice addition. I initially made it so spiders replaced air with cobweb and this made crystal biomes really dangerous, which I like. Then I thought of this but it seems like overkill now. Thanks for  putting the thought into it :)

**Comment by tenplus1** [comment]
Will look into this :)
