### ISSUE TITLE
Rotation ignored by the mount library

### ISSUE THREAD

**Issue by NPXcoot** [tenplus1/mobs_redo#40]
If you try to ride a mob that has self.rotate~=0 its model is not rotated when you are mounting it.
Is it possible to do something?
Thank you

**Comment by tenplus1** [comment]
Ideally mob models should be at 0 rotation for best compatibility but I'll have a look and see if attached models can be rotated.

**Comment by tenplus1** [comment]
Okies, it seems to be fixed now :)  I have mount functions check and use self.rotate to fix the mob rotation and added the line:
```
self.player_rotation = {x = 0, y = 90, z = 0}
```
... to the do_custom function with the other mount settings to rotate player properly.
