### ISSUE TITLE
Jump

### ISSUE THREAD

**Issue by paly2** [tenplus1/mobs_redo#47]
Hello, sorry for my bad English,
It seems that mobs can't jump anymore since 1f0969e6d374bf089728b1995e97a97b06b2f111...
[Short video of the bug](http://cloud.langg.net/jump.flv)

**Comment by tenplus1** [comment]
Hrm, I cannot reproduce this error, sheep follow me and can jump uphill ok...  Will double check everything to be sure.

**Comment by paly2** [comment]
It seems that the bug doesn't occur if the sheep didn't stop walking before jumping, so maybe giving it (or making sure it has) a "horizontal speed" in addition to a "vertical speed" when jumping would fix it?

**Comment by tenplus1** [comment]
Update to latest API, mobs moving uphill and following players is a lot better.

**Comment by paly2** [comment]
Thanks a lot, now they can jump!

Is it intentional that they can jump over fences?

**Comment by tenplus1** [comment]
In fixing the walking uphill they can now walk over fences also, so 2-high fences are needed to stop them.
