### ISSUE TITLE
Suggestion: Add pet loyalty so that a loyal pet will defend an owner being attacked

### ISSUE THREAD

**Issue by vaguelyAnonymous** [tenplus1/mobs_redo#49]
-- pet loyalty - will attack owner's attacker...
-- everything after "-- attack puncher and call other mobs for help" could be refactored - swiped from main animal logic
-- maybe pet should have a loyalty flag so that this can be toggled based on animal types?
minetest.register_on_punchplayer(
	function (player, hitter, time_from_last_punch, toolcap, dir, damage)
	
		local objs = minetest.get_objects_inside_radius(hitter:getpos(), 20)--magic 20?
		local obj = nil
		local ent = nil
		for n = 1, #objs do

			obj = objs[n]:get_luaentity()

			if obj then

				if obj ~= nil and obj.owner ~= nil and player:get_player_name() == obj.owner then
					ent = obj -- add test here to prove obj is definatively a mob_redo?
					-- attack puncher and call other mobs for help
					if ent.passive == false
					and ent.state ~= "flop"
					and ent.child == false
					and hitter:get_player_name() ~= ent.owner
					and not mobs.invis[ hitter:get_player_name() ] then

						-- attack whoever punched mob
						ent.state = ""
						do_attack(ent, hitter)

						-- alert others to the attack
						local objs = minetest.get_objects_inside_radius(hitter:getpos(), ent.view_range)
						local obj = nil

						for n = 1, #objs do

							obj = objs[n]:get_luaentity()

							if obj then

								if obj.group_attack == true
								and obj.state ~= "attack" then
									do_attack(obj, hitter)
								end
							end
						end
					end
				end
			end
		end
		
		return true
	end
)

**Comment by tenplus1** [comment]
Thanks for the idea, have implemented it another way.
