### ISSUE TITLE
Certain mobs from other projects spawn without limit when there is a world anchor

### ISSUE THREAD

**Issue by expertmm** [tenplus1/mobs_redo#52]
mobs version: git 2017-04-05
mobs_sky version: git 2015-09-29
technic version: 2017-03-15
Ubuntu Server 16.04 Xenial Xirrus

For some reason, mobs_sky keeps spawning more and more birds when there is a technic:admin_anchor (there are abm took too long errors in log even when noone is logged in, and when player gets near or in the chunk, hundreds of birds pour out of one block then are very gradually despawned). I would normally think this is a minetest engine problem, but this only happens with mobs_sky pack, and seemingly only with mobs_birds mod, and even then seems to only happen with gulls. I have tried to contact the author with no response. I cannot find anything unusual about how mobs redo is used by mobs_sky, except that:
nodes (in this case l_spawn_in) ={"air"}
However, the problem doesn't seem to happen with bats mods in the mobs_sky modpack which also has {"air"}, same active_object_count of 2, and similar max_height.
Do you think this is a minetest engine problem, or have any ideas?

mobs_birds from mobs_sky: [https://github.com/blert2112/mobs_sky/blob/master/mobs_birds/init.lua](https://github.com/blert2112/mobs_sky/blob/master/mobs_birds/init.lua)
technic:admin_anchor: [https://github.com/minetest-mods/technic/blob/master/technic/machines/other/anchor.lua](https://github.com/minetest-mods/technic/blob/master/technic/machines/other/anchor.lua)

**Comment by tenplus1** [comment]
Seems to be an issue with bird spawn numbers and chance.
