### ISSUE TITLE
new animations ideas and more animation variety

### ISSUE THREAD

**Issue by 22i** [tenplus1/mobs_redo#53]
- transition animation between passive mobs to aggressive  and agressive to passive: passagg, aggpass
- 2 new walking animations that get picked randomly to add variation to walking: walk1, walk2, walk3
- 1 more punch animation: punch3
- 2 more shooting animations: shoot1, shoot2, shoot3
- 5 standing animations for more variation:  stand1, stand2, stand3, stand4, stand5
- 3 jumping animations: jump1, jump2, jump3
- 3 swimming animations when mobs float in water: swim1, swim2, swim3,
- drowning animation
- transition animation between walking to flying: takeof
- landing animation
- 3 flying animations: fly1, fly2, fly3
- when mob is hit or damaged: hurt1, hurt2, hurt3
- mob spawning - animation when mob spawns: spawn1, spawn2, spawn3

animation tester an item to use on the mobs
to start a particular animation or a set of animations good for testing.

**Comment by tenplus1** [comment]
Will look into these :)
