### ISSUE TITLE
Mobs float in all liquids, even lava

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#55]
Mobs with `floats=1` will float on all liquids, even lava. I think it seems fairly odd for a cat or spider to float on top of lava.
What's worse, the mobs rarely even take lava damage for floating on top. Which means it is really hard to kill mobs by using a lava bucket. :D

I suggest:
* Add optional attribute `floats_in` which contains a list of nodes (bonus points: groups, too) in which to float
* If this attribute is nil (by default), mobs with `floats=1` only float in water (`group:water`), but nothing else

**Comment by tenplus1** [comment]
Changed to float in water only, will look into adding list.

**Comment by Wuzzy2** [comment]
Great!
