### ISSUE TITLE
Generalize environment damage

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#56]
A lot of the environment damage (lava, water) depends on hardcoded nodes or groups.
Whenever you have a damaging node which damages by `damage_per_second`, mobs just ignore it. You can have the death spikes of doom, but ALL mobs completely ignore it.
Also, requiring to set `lava_damage` for all mobs is doomed for inconsistency. Mob A will have 3 damage, mob B 10 damage, etc. although the modders actually wanted the *default* lava damage.

I suggest:
* Add attribute `node_damage` which is true by default (!). If `true`, entities take damage inside nodes with `damage_per_second` set, just like a player would. If `false`, the mob ignores `damage_per_second` completely (which is the current behaviour which I consider to be wrong)
* Remove the hardcoded fire damage
* Change the semantics of `water_damage` and `lava_damage`. The meaning of those will count as overrides. If not set, the entities take the same amount of damage as in the `damage_per_second` attribute of the node. If set, the `damage_per_second` is ignored and the set value is used as damage instead. If `node_damage` is `false`, water and lava damage default to 0 and must be set explicitly to enable damage.

These simple changes make it much easier to make mobs consistent. Modders can now safely leave out the damage attributes and only need to set them explicitly if they want to deviate from the defaults.

Please tell me if you agree with the ideas.

**Comment by tenplus1** [comment]
Nodes with damage_per_second hurts mobs now, 3d_armor disables some of these so will look into that.
