### ISSUE TITLE
new tab in creative mode inventory with all the registered mob spawn eggs

### ISSUE THREAD

**Issue by 22i** [tenplus1/mobs_redo#58]
<img src="http://i.imgur.com/z5XdpXR.png">

**Comment by Wuzzy2** [comment]
Where's the code for this? Or is this just concept art?

**Comment by 22i** [comment]
@Wuzzy2 just concept art made with gimp

**Comment by tenplus1** [comment]
Typing 'mobs' into creative search field brings up all mob eggs and items, so it would save me having to write this :)
