### ISSUE TITLE
Reversed riding controls with rotate=180

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#66]
If you have a mob with `rotate=180` and make it ridable, the controls are reversed.
If you press forwards, the mob goes backwards and vice-versa.
This happen despite the fact the mob is correctly facing forwards when you mounted it.

The controls seem to be broken with *any* non-default mob rotation.
If it is 90, the mob moves right (despite looking to the front) when pressing forwards, etc.

You can test this by rotating the pig model in `mobs_animal` by 180 degrees (optional, but it makes it easier to understand the bug) and then add `rotate=180` to the mob definition.

**Comment by tenplus1** [comment]
Ideally any mob models should be created facing forwards at 0 rotation but the weirder one's that do come through always need special attention when doing things like riding them...  Will look into this issue.
