### ISSUE TITLE
Death animation is randomly repeating for many mobs

### ISSUE THREAD

**Issue by 22i** [tenplus1/mobs_redo#67]
here is how it looks https://youtu.be/ytHvEo0KlJY

![skely](https://user-images.githubusercontent.com/17874916/27433796-6f6f39b0-5756-11e7-8fa0-78e75612256c.gif)

**Comment by tenplus1** [comment]
The death animation plays for 1 second before mob is removed, try slowing the frame rate down so it takes up the whole 1 second :)

**Comment by tenplus1** [comment]
Added animation flag for looping, e.g.  (die_start = 40, die_end = 65, die_loop = false)

**Comment by 22i** [comment]
@tenplus1 How do i slow the frame rate down? Does the death animation need to be 25 frames long or 30 frames or 60 frames?

**Comment by tenplus1** [comment]
using the example above: {die_start = 40, die_end = 65, die_speed = 15, die_loop = false}

**Comment by 22i** [comment]
i have also tested the death animation of development branch 2 https://github.com/NPXcoot/nssm/tree/development2
of not so simple mobs and experienced same death repeatings 
with mantis https://github.com/NPXcoot/nssm/blob/development2/mobs/mantis.lua

if animation always plays for 1 second then why does it sometimes repeat the animation and sometimes it doesnt? it might be that sometimes its longer than 1 second? Could it have something to do with lag? It could also be that it doesnt always start at start frame.

what does `die_speed = 15` exactly do to animation? is it 15x faster or slower compared to the speed of animation in blender - or is it 15% out of 100% of blender animation speed?

does the number difference between `die_start = 50` and `die_end = 60` make any difference? Like here the difference is 10 but it could also be 30 or 60.

@tenplus1

**Comment by tenplus1** [comment]
if die_start = 50 and die_end = 60 then it's using 10 frames for animation and die_speed = 15 means it plays 15 frames a second.
