### ISSUE TITLE
backface culling see mesh faces from all sides even inside

### ISSUE THREAD

**Issue by 22i** [tenplus1/mobs_redo#68]
to make it work add this line `backface_culling = def.backface_culling or false,` under https://github.com/tenplus1/mobs_redo/blob/master/api.lua#L2549

when false, it allows 3d model mesh faces to be seen from all sides even inside

right now its false by default but it would be better
if it were true by default but no idea how to make that happen

it would be nice to be able to choose precisely what cube in the model gets backface_culling = false in case you would want back face culling applied only to teeth cube and mouth cube.

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3927

![backfacefalse](https://user-images.githubusercontent.com/17874916/27432914-95379380-5752-11e7-9e91-13023ae9052d.png)
`backface_culling = false`
![backfacetrue](https://user-images.githubusercontent.com/17874916/27432922-9f99145c-5752-11e7-89fb-6c98f63166d5.png)
`backface_culling = true`

**Comment by tenplus1** [comment]
Why would anyone be inside a mob ?

**Comment by 22i** [comment]
`backface_culling = false`
see how all the bones can be seen you dont need to be inside the mob to see the effect
![horsebackfacefalse](https://user-images.githubusercontent.com/17874916/27454513-7152b11e-579a-11e7-92cd-a1e667aaaa51.png)
![horsebacfacetrue](https://user-images.githubusercontent.com/17874916/27454501-6ab75e68-579a-11e7-91ea-1644842cbcf4.png)
`backface_culling = true` some bones become invisible

this would be easily fixed in blender by copying every cube and flipping normals but for some cases it would be nice to have an option to just set mob to `backface_culling = false` without fliping normals in blender

**Comment by tenplus1** [comment]
turns out you can set backface_culling when adding textures to mobs e.g.:

textures = {
   {"mobs_skeleton_horse.png", backface_culling = false},
},
