### ISSUE TITLE
No drops or different drops for children

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#69]
Currently, all children have the same drops as their parents. For mob farming, this means that there is no point in letting a mob grow.

I suggest that children have no drops by default.

I also suggest an optional parameter `child_drops` which, when set, defines the list of drops while the mob is a child (same syntax as `drops`), for more customiztion.

**Comment by tenplus1** [comment]
Sorted, child mobs drop nothing until fully grown :)
