### ISSUE TITLE
Make mobs flee from other mobs and/or player

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#70]
Suggestion:

Add a new field into the mob definition with the name “`runaway_from`”.
This field is optional and holds a list of entities (including the special value `"player"` for players) that the mob will run away from when it is within the mob's view distance.

Example: `runaway_from = { "player", "mobs_example:scary_creature", "mobs_example:wizard_of_evil" }`

Also, the mob will never attempt to attack any entity (or the player, if specified) if it is in the `runaway_from` table.

This will be useful to create shy mobs.

**Comment by ErrorNull0** [comment]
I like this idea too. As the player becomes stronger, the weaker mobs will tend to run away instead of attacking like before. Perhaps 'stronger' simply means a player that has better armor or weapon equipped or has full health.

**Comment by tenplus1** [comment]
added
