### ISSUE TITLE
Rethink the type attribute

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#71]
Currently, all mobs must have a `type` attribute (`"animal"`, `"monster"` or `"npc"`).

But I think using this attribute is rather unwieldy and unflexible.

> Type "animal" is used for wandering mobs, "monster" for those that attack players (and some animals) and "npc" for those that can attack monsters...

This has various problems:

* It looks like the `type` attribute is redundant to `specific_attack`
* It seems it is impossible to define a mob which is always peaceful towards the player (even after attack) without being tamed but hostile towards other mobs

I suggest to rethink this attribute and maybe change or add other attributes to reflect all of the unique properties of each of the types. Also, `attack_animals` and `attacks_monsters` might need to be rethought as well. This would give more freedom in defining mobs. Maybe the real problem with `type` is that it conflates two distinct things:

1. How the mob behaves itself to other mobs
2. By which mobs this mob can be attacked (`attacks_monsters` and `attack_animal`)

I think number 1 should be removed.

Because `attack_animals` and `attacks_monsters` seem to be very useful attributes, those might be kept.
The meaning of `type` could be changed to be an entirely declarative one. Like a “category” which does not affect the behaviour of the mob itself. `type` could be then only be used to decide if it may be attacked by a different mob if `attack_animals` or `attacks_monsters` are set. The type “`npc`” might be ignored completely, then.

I don't know how these mob types work exactly, so please correct me for any nonsense suggestion I made. :D

**Comment by tenplus1** [comment]
The reason we have types is because Mobs Redo is compatible with the old Simple Mobs entities...  I kept it for a reason but will eventually phase it out through time.

**Comment by Wuzzy2** [comment]
Why did you close it? Don't you want to change this at all?

**Comment by tenplus1** [comment]
I will change it through time, but not just now.

**Comment by Wuzzy2** [comment]
If you intend to do this eventually, then please keep this issue open so it is not forgotten and overlooked by others.
