### ISSUE TITLE
Strange item group condition in mount.lua

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#72]
As of 8924b056233e76169e7a4e235ce95c7666bf417c, I have found this oddity in `mount.lua`, line 29:

    if minetest.get_item_group(node.name, "walkable") ~= 0 then

I have never seen the `walkable` group in the wild. Did you maybe mean the node definition field? Then you need to use `minetest.registered_nodes[node.name].walkable`. Otherwise, this code will probably never evaluate to true.

**Comment by tenplus1** [comment]
Whoopsie, fixed :)
