### ISSUE TITLE
Magic lasso is absurdly expensive

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#74]
Is there any reason why the magic lasso is so extremely expensive? You need 1 diamond block, 4 gold lumps and 4 strings.

If I understood correctly, the “magic” lasso is just a simple variant of the net with different durability and different capture chances. IMO that's hardly “magic” and doesn't justify the very high crafting cost.

I suggesst to make crafting cheaper and rename the item to “Lasso”.

**Comment by tenplus1** [comment]
Done...

**Comment by Wuzzy2** [comment]
Thanks. Out of curiosity, I still want to know why the recipe was so expensive. Why diamond and gold?
Does the (magic) lasso have an unique property I have missed?

**Comment by tenplus1** [comment]
it was going to set one point and I wanted players to lead animals to farms with food and not really use the lasso.
