### ISSUE TITLE
fall_speed is weird

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#76]
The `fall_speed` attribute is weird and not really useful.

I have hoped this attribute could be used to limit the maximum fall speed. As in, terminal velocity. When falling, it can not get faster than that.

But instead, this behaves very oddly by changing the … gravity? I don't know how this can be useful.
I suggest to change the semantics of `fall_speed` to be a simple limit of how fast a mob can fall. If this falling speed is reached, the mob won't accellerate, but instead fall at a constant speed until hitting the ground.

This can be useful for mobs to fall gracefully and I think this is much more practical than the current behaviour.

What do you think?

**Comment by tenplus1** [comment]
Fixed, falling velocity no longer exceeds fall_speed.
