### ISSUE TITLE
Add more callback functions

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#78]
I request to add more callback functions in the mob defintions. `self` is always the `ObjectRef` of the mob in question.

* [x] `on_punch(self, puncher, time_from_last_punch, tool_capabilities, dir)`: Same as for registered entities.
* [X] `on_replace(self, pos, oldnode, newnode)`: When the mob is about to replace `oldnode` at `pos`. `oldnode` is the current node, `newnode` is the node to set in place of the current node. If the the callback returns with `false`, the the node is not replaced
* [x] `on_breed(self, parents)`: Called when a child mob has just been created by breeding. `parents` is the table of its parents
* [x] `on_grow_up(self)`: Called when a child becomes an adult, either by growh or feeding

Example use cases:

* `on_punch`: Teleport away after attack
* `on_replace`: Sheep: Regrow wool after eating grass. Cow: Moo after eating grass
* `on_breed`: Customizing the child after birth, e.g. mix stats, textures, size, etc., based on the parent's “genome”

**Comment by tenplus1** [comment]
Added above functions with changed, on_breed(parent1, parent2)

**Comment by Wuzzy2** [comment]
Thank you very much!
