### ISSUE TITLE
Custom child mesh

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#79]
I propose to add the following attribute to the mob definition:

`child_mesh`

This expects a file name of a mesh. This mesh will be used while the mob is still a child. Similar to `child_texture`, but for mesh instead. By default, the default mesh is used.

**Comment by tenplus1** [comment]
Custom child meshes may have different collisionboxes and/or model sizes and would mess with internal checks, so instead I'll look into on_breed function so a proper baby version of a mob can be added with a timer to make it grow into a different mob entirely.

**Comment by Wuzzy2** [comment]
Well, the idea was that chilren have a different shape than adults instead of just differing in their size. For example, a larger head-to-body proportion.

You may want to require the child mesh to have the same dimensions as the adult mesh, and the scaling is done automatically by Mobs Redo.

**Comment by tenplus1** [comment]
Will look into that at some point and figure the best way to do it.
