### ISSUE TITLE
Add on_spawn callback in mobs:register_egg

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#80]
I suggest to add a new parameter to `mobs:register_egg`:

```mobs:register_egg(name, description, background, addegg, on_spawn)```

`on_spawn` has this syntax:

`on_spawn(self, pos, pointed_thing)`

* `self`: ObjectRef of new mob
* `pos`: Position in which the mob spawned
* `pointed_thing` Where the player clicked

This function is called right after the mob has been spawned with the spawn egg.
This callback will be useful to tweak mob properties after spawning.

Use cases:
- Set random model after spawning
- Spawn additional children around mob
- Set random texture based on surroundings, e.g. snow rabbit when spawned on snow block

**Comment by tenplus1** [comment]
on_spawn has been added into the mob registry to check things like this even if it has been spawned from egg.
