### ISSUE TITLE
Using a spawn egg on the bottom side of a node spawns mob above the node

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#81]
How to reproduce:

* Take a spawn egg, for example, a spawn egg of a sheep
* Find a ceiling somewhere
* Rightclick the bottom part of the ceiling to spawn the mob

The mob will spawn *above* the node you just clicked, rather than the node below. So the mob may end up inside solid nodes.

The bug can be best tested and observed by building a simple house with a 1-block high glass ceiling.

**Comment by tenplus1** [comment]
This one comes down to player choice, I could scan surrounding nodes and place on top properly but it takes away player placement by doing so and sometimes they want mobs inside a wall.

**Comment by Wuzzy2** [comment]
Uhhhh … what?
Why is it desired to spawn mobs inside solid nodes? Many mobs would just suffocate.

You don't need to scan any nodes, just spawn the mob [i]below[/b] the clicked surface so it isn't doomed to suffocate.

I think the use case “spawn mob in air” is more important than the use case “spawn mob inside wall so it suffocates”.
