### ISSUE TITLE
Interbreeding

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#82]
I suggest to make it possible to interbreed different animal species.

Currently, you can only breed mobs of the exact same type.

With interbreeding, it would be possible to breed 2 mobs of different types.
To enable interbreeding, this function must be called:

```
mobs:register_interbreed(parents, interbreed_result)
```

Enables interbreeding between two species.

* `parent1`, `parent2`: Parents to interbreed, in no particular order
* `interbreed_result`. Optional function, no parameters. This is called when breeding occours, right *before* the child spawns. It is used to select the entity type of the child. If this is `nil`, interbreeding will simply choose the species of a random parent.

Example and most obvious use case:
```
mobs:register_interbreed(
    "example:donkey", "example:horse",
    function()
        return "example:mule"
    end
)
```

Breeding a donkey and horse together results in a mule with 100% chance.

Silly example:
```
mobs:register_interbreed(
    "example:cat", "example:dog",
    function()
        if math.random(1,10) = 1 then
            return "example:catdog"
        else
            return "example:failed_experiment"
        end
    end
)
```

Breeding a cat and dog together results in a catdog with 10% chance and in a “failed experiment” with 90% chance.

Another example:
```
mobs:register_interbreed("example:blob", "example:hair_monster")
```
Enables interbreeding between blobs and hair monsters. The offspring will be either a blob or a hair monster, with 50% chance each.

**Comment by TekhnaeRaav** [comment]
I think this idea has potential, cause then you can have mobs of different traits yet still have them breed with similar species, or even not similar if you wanted!

**Comment by tenplus1** [comment]
on_breed function can be used as override and spawn mutations.
