### ISSUE TITLE
Set real maximum health

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#83]
I noticed the `hp_min` and `hp_max` parameters can be used to randomly choose the initial health, but not the maximum health.

E.g. with `hp_min=15` and `hp_max=30`, the *initial* health is between 15 and 30, but the maximum health is always at 30.
What if want the *maximum* health to randomly vary between mobs? It's not possible AFAIK.

Would it be possible to add additonal attributes for this use case?

**Comment by tenplus1** [comment]
'hp_max' is set for that mob type/species in itself but if you wanna change it to another value then you can using on_spawn function when registering mob:spawn

**Comment by Wuzzy2** [comment]
Sadly, this is a very limited solution. It does not work if the mob spawns via a spawn egg, with `/spawnentity`, `minetest.add_item` or by breeding.

See #84.
