### ISSUE TITLE
Add on_spawn into mob definition

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#84]
I suggest to add a new attribute to mob definitions, `on_spawn`. This is a function:

`on_spawn(self, pos)`

* `self`: ObjectRef of new mob
* `pos`: Position in which the mob spawned

This function is called right after the mob has been spawned *if* neither `on_spawn` of a spawn egg (see #80) or `on_spawn` of `mobs:spawn_specific` (and friends) was called, or those functions do not exist.
If the mob spawns from a spawn egg, and the spawn egg has `on_spawn` defined, only the spawn egg's function is executed.
If the mob is spawned from `mobs:spawn_specific` (and friends) and `on_spawn` is defined, only this function gets executed.

This makes `on_spawn` in the mob defintion mostly a convenience and “fallback” function, but it also fills gaps: `/spawnentity`, `minetest.add_entity`.
The biggest benefit of this function will be that it is a easy and reliable to catch the spawning of a mob.

Related issue: #80 (`on_spawn` for spawn eggs)

**Comment by tenplus1** [comment]
added.
