### ISSUE TITLE
fall_speed changes gravity

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#86]
The problem with `fall_speed` is that it apparently changes the gravity for the mob. This is not a good idea IMO.

The biggest problem with this is that this also greatly increases the jump height for no reason. This makes setting `fall_speed` useless for most real-world applications.

Use case example:
I want to have a chicken which falls gracefully with a maximum speed of X. But if I just set `fall_speed=X`, this mostly just affects gravity, allowing it to jump higher.

What I wish is that `fall_speed` *just* alters the terminal falling velocity of the mob, but does *not* affect gravity or anything else. Also, I think the arbitrary limits (-10 and -2) could be removed.

**Comment by tenplus1** [comment]
It only affects the falling speed of the mob in question so that it will never go over the 'fall_speed' limit, it doesnt increase jump height at all.

**Comment by Wuzzy2** [comment]
Uhm … you're wrong. Have you even tested this?!

Just set `fall_speed=-2` for `mobs_animal:chicken` and see what happens when the chicken wants to jump.

Tested in `mobs` a964aa028d462d66e50754c7eeef4519fa93d892` and modified `mobs_animal` ebc2e3a8742a18e219ef56ebeadb1080f919017d.

**Comment by tenplus1** [comment]
Why have fall speed at -2 ? but re-ordered falling valocity checks, should work ok now.

**Comment by Wuzzy2** [comment]
Thanks, it works now like expected. :+1:

`-2` was just an example because the effect is clearly visible, then.
