### ISSUE TITLE
Too many chat messages

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#89]
I think this mod produces too many chat messages. I generally dislike mods if they spam the chat. Ideally a mod should normally not use the chat at all, but if it does, it must do *very* sparingly, because it disrupts the regular chat.

I understand the need to make the player somehow aware of events, but ideally this is done by some means other than the chat, if possible. This could be done by audiovisual effects or a mob animation.

Things with chat message spam:
* You try to protect or capture a mob which is not tamed
* You feed a mob
* You tamed a mob
* Mob is owned by someone else.

An example for a good audiovisual effect are the heart particles when in love mode. There is no chat message for love mode because it is not needed. I like to see this mod go into that direction.

Some ideas for audiovisual effects:
* The mob performs a special reaction or makes a sound
* Eating sound when successfully fed a mob
* Mob sound for successful / failed capture
* Sound and particles for protecting a mob (https://github.com/tenplus1/mobs_redo/pull/88)
* Mob screams (unique sound effect) and runs away when a capture attempt failed, or it performs an unique animation (depends on mob definition)

It is also questionable if certain events need any notification at all, like feeding a mob to full health. I think some of the messages can be removed completely.

My list of ideas is not complete, this issue is about eliminating the chat messages in favor of other notification measures. I don't have ideas for every possible event yet.

**Comment by tenplus1** [comment]
Particles added for rune protection and sounds, will need to think of appropriate particles for other things to lessen text messages, and if possible I don't want too many sfx.
