### ISSUE TITLE
Mob mesh model attachments?

### ISSUE THREAD

**Issue by 22i** [tenplus1/mobs_redo#90]
is it possible for an entity to use many models not just one? This would come in handy for mobs holding different items, mobs sitting on other mobs like spiderjockey

it could be that you define from mesh1 to mesh5 to different models and when you spawn that mob it would consist of all the models you defined

What about mob model attachments can we attach different models to certain points or bones?

**Comment by tenplus1** [comment]
I have only ever linked players with entities like boats/cart etc. and never mobs, will look into it.
