### ISSUE TITLE
Sound files violate naming conventions

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#91]
Why did you change the file names of the sounds I posted in my recent mob protection rune PR? :-(

Now the sounds are violating naming conventions because of this.

Quote from `lua_api.txt`:

> Textures
> --------
> Mods should generally prefix their textures with `modname_`, e.g. given
> the mod name `foomod`, a texture could be called:
> 
>     foomod_foothing.png

I assume the same applies for models and sounds.

Also, “Creative Commons” is not a license. There a several Creative Commons license, some of them free, some of them not.
Note: If those 2 sounds are under CC0, its “anything goes”, so it's compatible with the MIT License.

**Comment by tenplus1** [comment]
Sorted.
