### ISSUE TITLE
Change pathfinder algorithm to A*_noprefetch?

### ISSUE THREAD

**Issue by Wuzzy2** [tenplus1/mobs_redo#93]
I am a bit surprised by this code line:

```
self.path.way = minetest.find_path(s, p1, 16, self.stepheight, dropheight, "Dijkstra")
```

May I ask why Dijstra was chosen over A*_noprefetch (the default algorithm)?

**Comment by tenplus1** [comment]
the current path finding string seems to find location in Less steps.

**Comment by Wuzzy2** [comment]
Sooo, you won't change the algorithm?

**Comment by tenplus1** [comment]
I don't see any advantages in changing, Dijkstra works well and sometimes in less steps.
