### ISSUE TITLE
The sound of mobs walking / swimming can be heard from too far away

### ISSUE THREAD

**Issue by leorockway** [tenplus1/mobs_redo#98]
The sound of mobs can be heard from too far away which means that if you're in your house and there are mobs some 30 blocks away you can still hear them swimming, or walking on dirt or walking on snow and if there are many mobs it gets pretty overwhelming.
I reported this to mc_mobs (https://github.com/maikerumine/mobs_mc/issues/109) and it was explained to me that this was a mobs_redo issue.

**Comment by tenplus1** [comment]
Thats nothing to do with the mobs api but the entity part of minetest engine and enabling footsteps.
