### ISSUE TITLE
Request: Single setting to adjust all spawn rates

### ISSUE THREAD

**Issue by cessna151** [tenplus1/mobs_redo#99]
It would be nice to have a minetest.conf setting such that it will adjust the spawn rate of all registered mobs. A simple multiplier would work nicely, for example:

spawn_rate = 1  # Setting this to .5 would reduce the total number of spawns of each mob by half, or setting to 3 would triple the number of spawns. 

This way each mob could still be configured separately; for example, if the default spawn rate for cows is 3 times higher than cats, you would still have the same ratio but the overall spawn rate could be increased/decreased. 
:large_orange_diamond:

**Comment by tenplus1** [comment]
I'd rather you use the already existing mob spawn settings for minetest.conf as this change would add a further setting to the game which would only confuse... use:

-- change cow spawn chance to 1000 with 5 cows per area allowed
mobs_animal:cow = 1000, 5

**Comment by cessna151** [comment]
Using that method is very tedious. I must look into the code for every single mob and then write a separate setting for every single mob. That also requires coding knowledge. (i'm not a coder) I do not know how to adjust the setting to achieve what i want. My suggestion solves both issues, and is very unlikely to cause any confusion.

Thanks for your consideration.
:large_orange_diamond:

**Comment by aerozoic** [comment]
fixed :) https://github.com/tenplus1/mobs_redo/commit/93ca01de003d132cb09c73740faf7e5df229f11a
:large_orange_diamond:
